# Generated by Django 5.1.6 on 2025-02-07 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0004_delete_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-date_added'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
